version: '3.1'

services:
  mysql:
    image: mysql:8.0.32
    container_name: container_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3306:3306

  api:
    container_name: api
    image: node:16
    restart: always
    ports:
      - 3001:3001
      - 9229:9229
    user: node
    environment:
      - SQL_HOST=mysql
      - SQL_USERNAME=root
      - SQL_PASSWORD=1234
      - JWT_SECRET=batatinha123
      - PORT=3001
    volumes:
      - ./:/app
    working_dir: /app
    command: bash # note que o containter já vai iniciar a aplicação
    # As duas opções abaixo correspondem ao -it
    tty: true # -t
    stdin_open: true #-i 
    depends_on:
      - mysql
