version: '3'
services:
  node:
    image: node:16-alpine
    container_name: simpsons_api
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=simpsons_db
      - PORT=3000
    depends_on:
      - "database"

  database:
    container_name: simpsons_db
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simpsons_db
    ports:
      - "3306:3306"
